"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l7v*$s^7#@zcc(36h82!vn+$cqei!3hg!+xxd*ah(y@v$fb@!f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Security Settings

# SECURE_SSL_REDIRECT: Redirects all HTTP requests to HTTPS. 
# This is crucial for protecting data in transit.
SECURE_SSL_REDIRECT = True

# SECURE_HSTS_SECONDS: The duration (in seconds) that the browser should 
# remember to only access the site via HTTPS. 31536000 seconds is 1 year.
SECURE_HSTS_SECONDS = 31536000

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Ensures that the HSTS policy applies to 
# all subdomains of the current domain.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allows the site to be submitted to the HSTS preload list 
# maintained by browser vendors.
SECURE_HSTS_PRELOAD = True

# SESSION_COOKIE_SECURE: Ensures that session cookies are only sent over 
# secure (HTTPS) connections.
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE: Ensures that CSRF cookies are only sent over 
# secure (HTTPS) connections, protecting against cross-site request forgery.
CSRF_COOKIE_SECURE = True

# X_FRAME_OPTIONS: Prevents the site from being rendered inside a <frame>, 
# <iframe>, or <object> to protect against clickjacking attacks.
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents the browser from MIME-sniffing the response 
# away from the declared content-type, reducing exposure to drive-by downloads.
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enables the browser's XSS filter to help 
# prevent cross-site scripting attacks.
SECURE_BROWSER_XSS_FILTER = True

# Content Security Policy
# CSP_DEFAULT_SRC: Defines the default policy for fetching resources.
CSP_DEFAULT_SRC = ("'self'",)
# CSP_STYLE_SRC: Restricts the sources of Stylesheets.
CSP_STYLE_SRC = ("'self'",)
# CSP_SCRIPT_SRC: Restricts the sources of JavaScript.
CSP_SCRIPT_SRC = ("'self'",)
